import type { Flow, PaletteItem } from './types';

export const PALETTE: PaletteItem[] = [
  { kind: 'hotkey', label: 'Global Hotkey', cat: 'trigger', icon: 'keyboard', color: '#0078D4', desc: 'Ctrl+Alt+?' },
  { kind: 'window_focus', label: 'Window Focus', cat: 'trigger', icon: 'window', color: '#0078D4', desc: 'window activated' },
  { kind: 'schedule', label: 'Scheduled', cat: 'trigger', icon: 'clock', color: '#0078D4', desc: 'interval / time' },
  { kind: 'at_time', label: 'At Time', cat: 'trigger', icon: 'clock', color: '#0078D4', desc: 'cron at 09:00' },
  { kind: 'file_watcher', label: 'File Watcher', cat: 'trigger', icon: 'file', color: '#0078D4', desc: 'file changed' },
  { kind: 'startup', label: 'On Startup', cat: 'trigger', icon: 'power', color: '#0078D4', desc: 'app launch' },
  { kind: 'clipboard', label: 'Clipboard Change', cat: 'trigger', icon: 'copy', color: '#0078D4', desc: 'text copied' },
  { kind: 'send_keys', label: 'Send Keystrokes', cat: 'action', icon: 'type', color: '#4A5568', desc: 'type text' },
  { kind: 'mouse_click', label: 'Mouse Click', cat: 'action', icon: 'mouse', color: '#2B3A55', desc: 'click at x,y' },
  { kind: 'mouse_move', label: 'Mouse Move', cat: 'action', icon: 'move', color: '#2B3A55', desc: 'move cursor' },
  { kind: 'close_app', label: 'Close App', cat: 'action', icon: 'x', color: '#D13438', desc: 'kill process' },
  { kind: 'open_url', label: 'Open URL', cat: 'action', icon: 'globe', color: '#0078D4', desc: 'launch browser' },
  { kind: 'take_screenshot', label: 'Screenshot', cat: 'action', icon: 'camera', color: '#E01765', desc: 'save display' },
  { kind: 'ocr_screen', label: 'OCR Screen', cat: 'action', icon: 'eye', color: '#E01765', desc: 'read text via OCR' },
  { kind: 'find_image', label: 'Find Image', cat: 'action', icon: 'search', color: '#2B3A55', desc: 'locate on screen' },
  { kind: 'powershell', label: 'Run Script', cat: 'action', icon: 'terminal', color: '#0F6CBD', desc: 'PowerShell' },
  { kind: 'delay', label: 'Wait', cat: 'action', icon: 'timer', color: '#5C6370', desc: 'pause ms' },
  { kind: 'condition', label: 'Condition', cat: 'action', icon: 'branch', color: '#D83B01', desc: 'if / else' },
  { kind: 'notification', label: 'Notification', cat: 'action', icon: 'bell', color: '#107C10', desc: 'toast' },
  { kind: 'open_app', label: 'Launch App', cat: 'action', icon: 'send', color: '#8764B8', desc: 'open program' },
  { kind: 'focus_window', label: 'Focus Window', cat: 'action', icon: 'eye', color: '#8764B8', desc: 'bring to front' },
  { kind: 'clipboard_set', label: 'Set Clipboard', cat: 'action', icon: 'clipboard', color: '#8764B8', desc: 'write text' },
  { kind: 'http_request', label: 'HTTP Request', cat: 'action', icon: 'globe', color: '#0F6CBD', desc: 'GET/POST API' },
  { kind: 'file_write', label: 'Write File', cat: 'action', icon: 'terminal', color: '#107C10', desc: 'save text' },
  { kind: 'play_sound', label: 'Play Sound', cat: 'action', icon: 'bell', color: '#E01765', desc: 'beep alert' },
  { kind: 'web_search', label: 'Web Search', cat: 'action', icon: 'search', color: '#0078D4', desc: 'instant search' },
  { kind: 'repeat', label: 'Loop / Repeat', cat: 'action', icon: 'refresh', color: '#D83B01', desc: 'repeat N times' },
  { kind: 'for_each', label: 'For Each', cat: 'action', icon: 'refresh', color: '#D83B01', desc: 'loop each item' },
  { kind: 'json_parse', label: 'JSON Parse', cat: 'action', icon: 'braces', color: '#0F6CBD', desc: 'parse JSON' },
  { kind: 'lock_pc', label: 'Lock PC', cat: 'action', icon: 'shield', color: '#5C6370', desc: 'lock workstation' },
  { kind: 'volume_control', label: 'Volume', cat: 'action', icon: 'bell', color: '#107C10', desc: 'set volume %' },
];

export const VARIABLES = [
  { token: '{CLIPBOARD}', type: 'string', desc: 'current clipboard text' },
  { token: '{DATE}', type: 'string', desc: 'system date · yyyy-MM-dd' },
  { token: '{TIME}', type: 'string', desc: 'system time · HH:mm:ss' },
  { token: '{ACTIVE_WINDOW}', type: 'string', desc: 'focused window title' },
  { token: '{USER}', type: 'string', desc: 'current username' },
  { token: '{DOCS_PATH}', type: 'string', desc: 'Documents folder path' },
  { token: '{OCR_TEXT}', type: 'string', desc: 'last OCR result' },
  { token: '{JSON_VALUE}', type: 'string', desc: 'last JSON parse result' },
];

export const DEFAULT_FLOWS: Flow[] = [
  {
    id: 'flow-matrix',
    name: '⚡ Matrix Cyber Audit & System Patrol (Loop Demo)',
    description: 'Launches Matrix CMD, runs a 3-step ping loop with sound alerts, captures screenshot & logs report',
    enabled: true,
    nodes: [
      { id: 't1', kind: 'hotkey', category: 'trigger', label: 'Start Patrol', x: 40, y: 150, config: { hotkey: 'Run' }, color: '#0078D4', icon: 'keyboard' },
      { id: 'a1_notify', kind: 'notification', category: 'action', label: 'Notify Start', x: 240, y: 150, config: { title: 'Cyber Patrol', body: 'Starting Matrix System Audit...' }, color: '#107C10', icon: 'bell' },
      { id: 'a2_cmd', kind: 'open_app', category: 'action', label: 'Launch CMD', x: 440, y: 150, config: { exe: 'cmd.exe' }, color: '#8764B8', icon: 'send' },
      { id: 'a3_delay', kind: 'delay', category: 'action', label: 'Wait CMD', x: 640, y: 150, config: { ms: '1200' }, color: '#5C6370', icon: 'timer' },
      { id: 'a4_focus', kind: 'focus_window', category: 'action', label: 'Focus CMD', x: 840, y: 150, config: { title: 'cmd.exe' }, color: '#8764B8', icon: 'eye' },
      { id: 'a5_init', kind: 'send_keys', category: 'action', label: 'Init Matrix Theme', x: 1040, y: 150, config: { keys: 'color 0A{ENTER}title MATRIX CYBER PATROL{ENTER}cls{ENTER}' }, color: '#4A5568', icon: 'type' },
      { id: 'a6_loop', kind: 'repeat', category: 'action', label: 'Loop Patrol (3x)', x: 1240, y: 150, config: { count: '3' }, color: '#D83B01', icon: 'branch' },
      { id: 'a7_ping', kind: 'send_keys', category: 'action', label: 'Ping & Audit', x: 1440, y: 150, config: { keys: 'echo [PATROL {TIME}] Auditing Node...{ENTER}ping -n 2 127.0.0.1 > nul{ENTER}' }, color: '#4A5568', icon: 'type' },
      { id: 'a8_sound', kind: 'play_sound', category: 'action', label: 'Sound Alert', x: 1640, y: 150, config: {}, color: '#E01765', icon: 'bell' },
      { id: 'a9_shot', kind: 'take_screenshot', category: 'action', label: 'Capture Screen', x: 1840, y: 150, config: { filename: 'matrix_audit.png' }, color: '#E01765', icon: 'camera' },
      { id: 'a10_log', kind: 'file_write', category: 'action', label: 'Log Report', x: 2040, y: 150, config: { path: '{DOCS_PATH}\\matrix_patrol.log', content: 'Patrol Completed at {DATE} {TIME} by user {USER}' }, color: '#107C10', icon: 'terminal' },
      { id: 'a11_done', kind: 'notification', category: 'action', label: 'Notify Finish', x: 2240, y: 150, config: { title: 'Audit Complete', body: 'Report and screenshot saved to Documents!' }, color: '#107C10', icon: 'bell' },
    ],
    edges: [
      { from: 't1', to: 'a1_notify' },
      { from: 'a1_notify', to: 'a2_cmd' },
      { from: 'a2_cmd', to: 'a3_delay' },
      { from: 'a3_delay', to: 'a4_focus' },
      { from: 'a4_focus', to: 'a5_init' },
      { from: 'a5_init', to: 'a6_loop' },
      { from: 'a6_loop', to: 'a7_ping' },
      { from: 'a7_ping', to: 'a8_sound' },
      { from: 'a8_sound', to: 'a6_loop' },
      { from: 'a6_loop', to: 'a9_shot' },
      { from: 'a9_shot', to: 'a10_log' },
      { from: 'a10_log', to: 'a11_done' },
    ],
  },
  {
    id: 'flow-1',
    name: 'Web Search Automation',
    description: 'Opens DuckDuckGo, focuses browser, and types search query automatically',
    enabled: true,
    nodes: [
      { id: 't1', kind: 'hotkey', category: 'trigger', label: 'Trigger', x: 40, y: 150, config: { hotkey: 'Run' }, color: '#0078D4', icon: 'keyboard' },
      { id: 'a1', kind: 'open_url', category: 'action', label: 'Open DuckDuckGo', x: 260, y: 150, config: { url: 'https://duckduckgo.com' }, color: '#8764B8', icon: 'send' },
      { id: 'a2', kind: 'delay', category: 'action', label: 'Wait for load', x: 480, y: 150, config: { ms: '2500' }, color: '#5C6370', icon: 'timer' },
      { id: 'a2_focus', kind: 'focus_window', category: 'action', label: 'Focus Browser', x: 700, y: 150, config: { title: 'DuckDuckGo' }, color: '#8764B8', icon: 'eye' },
      { id: 'a3', kind: 'send_keys', category: 'action', label: 'Search query', x: 920, y: 150, config: { keys: 'MacroFlow automation tool{ENTER}' }, color: '#4A5568', icon: 'type' },
    ],
    edges: [
      { from: 't1', to: 'a1' },
      { from: 'a1', to: 'a2' },
      { from: 'a2', to: 'a2_focus' },
      { from: 'a2_focus', to: 'a3' },
    ],
  },
  {
    id: 'flow-2',
    name: 'CMD Automations',
    description: 'Sets clipboard, checks condition, and uses CMD robustly',
    enabled: true,
    nodes: [
      { id: 't1', kind: 'hotkey', category: 'trigger', label: 'Trigger', x: 40, y: 150, config: { hotkey: 'Run' }, color: '#0078D4', icon: 'keyboard' },
      { id: 'a1', kind: 'clipboard_set', category: 'action', label: 'Set Clipboard', x: 260, y: 150, config: { value: '777' }, color: '#8764B8', icon: 'clipboard' },
      { id: 'a2', kind: 'condition', category: 'action', label: 'Clipboard has text?', x: 480, y: 150, config: { expr: 'len({CLIPBOARD}) > 0', then: 'a3', else: 'a5' }, color: '#D83B01', icon: 'branch' },
      { id: 'a3', kind: 'open_app', category: 'action', label: 'Open CMD (THEN)', x: 740, y: 40, config: { exe: 'cmd.exe' }, color: '#8764B8', icon: 'send' },
      { id: 'a3_delay', kind: 'delay', category: 'action', label: 'Wait for CMD', x: 960, y: 40, config: { ms: '1000' }, color: '#5C6370', icon: 'timer' },
      { id: 'a3_focus', kind: 'focus_window', category: 'action', label: 'Focus CMD', x: 1180, y: 40, config: { title: 'cmd.exe' }, color: '#8764B8', icon: 'eye' },
      { id: 'a4', kind: 'send_keys', category: 'action', label: 'Type command', x: 1400, y: 40, config: { keys: 'color 0A{ENTER}echo HELLO FROM MACROFLOW!{ENTER}' }, color: '#4A5568', icon: 'type' },
      { id: 'a5', kind: 'notification', category: 'action', label: 'Notify (ELSE)', x: 740, y: 220, config: { title: 'Empty', body: 'Clipboard was empty' }, color: '#107C10', icon: 'bell' },
    ],
    edges: [
      { from: 't1', to: 'a1' },
      { from: 'a1', to: 'a2' },
      { from: 'a2', to: 'a3' },
      { from: 'a3', to: 'a3_delay' },
      { from: 'a3_delay', to: 'a3_focus' },
      { from: 'a3_focus', to: 'a4' },
      { from: 'a2', to: 'a5' },
    ],
  },
  {
    id: 'flow-ocr',
    name: '🔍 OCR Invoice Scanner Pro',
    description: 'High-accuracy OCR (Tesseract/WinRT) → clipboard → JSON parse → For Each loop → secure save',
    enabled: true,
    nodes: [
      { id: 't1', kind: 'hotkey', category: 'trigger', label: 'Scan Trigger', x: 40, y: 80, config: { hotkey: 'Run' }, color: '#0078D4', icon: 'keyboard' },
      { id: 'a1_ocr', kind: 'ocr_screen', category: 'action', label: 'OCR Screen', x: 260, y: 80, config: { lang: 'eng', psm: '6', region: 'full' }, color: '#E01765', icon: 'eye' },
      { id: 'a2_clip', kind: 'clipboard_set', category: 'action', label: 'Copy OCR', x: 480, y: 80, config: { value: '{OCR_TEXT}' }, color: '#8764B8', icon: 'clipboard' },
      { id: 'a3_json', kind: 'json_parse', category: 'action', label: 'Parse JSON', x: 700, y: 80, config: { json: '{"invoice":"INV-2024-001","total":299.99,"notes":"{OCR_TEXT}"}', path: '$.total' }, color: '#0F6CBD', icon: 'braces' },
      { id: 'a4_each', kind: 'for_each', category: 'action', label: 'For Each Line', x: 920, y: 80, config: { items: '{OCR_TEXT}', delimiter: '\\n' }, color: '#D83B01', icon: 'refresh' },
      { id: 'a5_write', kind: 'file_write', category: 'action', label: 'Save Report', x: 1140, y: 80, config: { path: '{DOCS_PATH}\\ocr_report.txt', content: 'OCR at {DATE} {TIME}: {OCR_TEXT} | JSON: {JSON_VALUE}' }, color: '#107C10', icon: 'terminal' },
      { id: 'a6_notify', kind: 'notification', category: 'action', label: 'Done', x: 1360, y: 80, config: { title: 'OCR Complete', body: 'Extracted {OCR_TEXT}' }, color: '#107C10', icon: 'bell' },
      { id: 'a7_lock', kind: 'lock_pc', category: 'action', label: 'Lock PC', x: 1580, y: 80, config: {}, color: '#5C6370', icon: 'shield' },
    ],
    edges: [
      { from: 't1', to: 'a1_ocr' },
      { from: 'a1_ocr', to: 'a2_clip' },
      { from: 'a2_clip', to: 'a3_json' },
      { from: 'a3_json', to: 'a4_each' },
      { from: 'a4_each', to: 'a5_write' },
      { from: 'a5_write', to: 'a6_notify' },
      { from: 'a6_notify', to: 'a7_lock' },
    ],
  },
  {
    id: 'flow-ocr-quick',
    name: '🔍 OCR Quick Demo — Read Screen in 1 Click',
    description: 'Perfect for beginners: press Run → OCR captures screen → shows text → saves to Documents\\ocr_quick.txt',
    enabled: true,
    nodes: [
      { id: 't1', kind: 'hotkey', category: 'trigger', label: 'Press to Scan', x: 40, y: 100, config: { hotkey: 'Run' }, color: '#0078D4', icon: 'keyboard' },
      { id: 'a1_ocr', kind: 'ocr_screen', category: 'action', label: 'OCR Full Screen', x: 260, y: 100, config: { lang: 'eng', psm: '6', region: 'full' }, color: '#E01765', icon: 'eye' },
      { id: 'a2_check', kind: 'condition', category: 'action', label: 'Found Text?', x: 480, y: 100, config: { expr: 'len({OCR_TEXT}) > 0', then: 'a3_ok', else: 'a3_empty' }, color: '#D83B01', icon: 'branch' },
      { id: 'a3_ok', kind: 'notification', category: 'action', label: 'Show Text', x: 740, y: 40, config: { title: 'OCR Success', body: '{OCR_TEXT}' }, color: '#107C10', icon: 'bell' },
      { id: 'a4_save', kind: 'file_write', category: 'action', label: 'Save to File', x: 960, y: 40, config: { path: '{DOCS_PATH}\\ocr_quick.txt', content: '[{DATE} {TIME}] OCR: {OCR_TEXT}' }, color: '#107C10', icon: 'terminal' },
      { id: 'a3_empty', kind: 'notification', category: 'action', label: 'No Text', x: 740, y: 180, config: { title: 'OCR Empty', body: 'No text detected — try larger font or spa lang' }, color: '#D13438', icon: 'bell' },
    ],
    edges: [
      { from: 't1', to: 'a1_ocr' },
      { from: 'a1_ocr', to: 'a2_check' },
      { from: 'a2_check', to: 'a3_ok' },
      { from: 'a3_ok', to: 'a4_save' },
      { from: 'a2_check', to: 'a3_empty' },
    ],
  },
  {
    id: 'flow-watcher',
    name: '📁 File Watcher — Auto OCR on New File',
    description: 'Watches Documents\\watch.txt → on change runs OCR → saves report — perfect for hot folders',
    enabled: true,
    nodes: [
      { id: 't1', kind: 'file_watcher', category: 'trigger', label: 'Watch File', x: 40, y: 100, config: { path: '{DOCS_PATH}\\watch.txt', interval: '1000' }, color: '#0078D4', icon: 'file' },
      { id: 'a1_ocr', kind: 'ocr_screen', category: 'action', label: 'OCR Screen', x: 260, y: 100, config: { lang: 'spa', psm: '6', region: 'full' }, color: '#E01765', icon: 'eye' },
      { id: 'a2_cond', kind: 'condition', category: 'action', label: 'Has Text?', x: 480, y: 100, config: { expr: 'len({OCR_TEXT}) > 0', then: 'a3_notify', else: 'a3_empty' }, color: '#D83B01', icon: 'branch' },
      { id: 'a3_notify', kind: 'notification', category: 'action', label: 'Notify OCR', x: 740, y: 40, config: { title: 'Watcher: New Text', body: '{OCR_TEXT}' }, color: '#107C10', icon: 'bell' },
      { id: 'a4_save', kind: 'file_write', category: 'action', label: 'Append Log', x: 960, y: 40, config: { path: '{DOCS_PATH}\\watcher_log.txt', content: '[{DATE} {TIME}] Watcher OCR: {OCR_TEXT}' }, color: '#107C10', icon: 'terminal' },
      { id: 'a3_empty', kind: 'notification', category: 'action', label: 'Empty', x: 740, y: 180, config: { title: 'Watcher Empty', body: 'File changed but OCR empty' }, color: '#D13438', icon: 'bell' },
    ],
    edges: [
      { from: 't1', to: 'a1_ocr' },
      { from: 'a1_ocr', to: 'a2_cond' },
      { from: 'a2_cond', to: 'a3_notify' },
      { from: 'a3_notify', to: 'a4_save' },
      { from: 'a2_cond', to: 'a3_empty' },
    ],
  },
  {
    id: 'flow-json',
    name: '🔄 JSON & For Each — Process API Data',
    description: 'HTTP GET → JSON Parse $.data → For Each item → save + notify — template for APIs',
    enabled: true,
    nodes: [
      { id: 't1', kind: 'hotkey', category: 'trigger', label: 'Fetch Data', x: 40, y: 100, config: { hotkey: 'Run' }, color: '#0078D4', icon: 'keyboard' },
      { id: 'a1_http', kind: 'http_request', category: 'action', label: 'GET API', x: 260, y: 100, config: { url: 'https://api.example.com/data', method: 'GET', headers: '', body: '' }, color: '#0F6CBD', icon: 'globe' },
      { id: 'a2_json', kind: 'json_parse', category: 'action', label: 'Parse JSON', x: 480, y: 100, config: { json: '{"data":["a","b","c"], "total":3}', path: '$.data' }, color: '#0F6CBD', icon: 'braces' },
      { id: 'a3_each', kind: 'for_each', category: 'action', label: 'For Each', x: 700, y: 100, config: { items: '{JSON_VALUE}', delimiter: ',' }, color: '#D83B01', icon: 'refresh' },
      { id: 'a4_write', kind: 'file_write', category: 'action', label: 'Save Item', x: 920, y: 100, config: { path: '{DOCS_PATH}\\json_items.txt', content: 'Item: {JSON_VALUE} at {TIME}' }, color: '#107C10', icon: 'terminal' },
      { id: 'a5_notify', kind: 'notification', category: 'action', label: 'Done', x: 1140, y: 100, config: { title: 'JSON Done', body: 'Processed {JSON_VALUE}' }, color: '#107C10', icon: 'bell' },
    ],
    edges: [
      { from: 't1', to: 'a1_http' },
      { from: 'a1_http', to: 'a2_json' },
      { from: 'a2_json', to: 'a3_each' },
      { from: 'a3_each', to: 'a4_write' },
      { from: 'a4_write', to: 'a5_notify' },
    ],
  },
];
